# Use an official Node.js image as a base
FROM node:14 as build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project directory into the container
COPY . .

# Build the React app
# RUN npm run build

# Use Nginx as a lightweight web server
# FROM nginx:alpine

# # Copy the built React app from the build stage to the Nginx web server directory
# COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 3000

# Start Nginx server when the container starts
# CMD ["nginx", "-g", "daemon off;"]
CMD ["npm", "start"]