apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cicd-hackathondeploy
serialPipeline:
  stages:
  - targetId: dev
    # profiles:
    # - target-1
  - targetId: prod
    # profiles:
    # - target-2